### PR TITLE
Added range check to the steps in the mix tool

### PR DESCRIPTION
**Pull request by santiagovrancovich**
Added a function to check if the number of steps that the user wants to introduce is valid, otherwise it will return the closest value inside the range. This will ensure that the input is always valid.

### CODE REVIEW

**Comment by pabueco** [comment]
@santiagovrancovich First of all thanks for the PR! 

Although I like your implementation and there's nothing wrong with it, it would probably be a bit more straight forward and require less code if we would use the `clamp` function from lodash here instead. That way we can remove the checks and simply limit the value to a valid range when updating the query.

It would also be nice if you could define a const like `MAX_STEP_COUNT` on top and use that instead of the magic number 50. ;)

Another minor thing I noticed is that now that we're limiting the number of steps to be at least 2 we can't type something like `10` or `15` into the steps input because it's immediately changed to 2. But you don't have to tackle that if you don't want to.

Appreciate your contribution!

**Comment by santiagovrancovich** [comment]
> Although I like your implementation and there's nothing wrong with it, it would probably be a bit more straight forward and require less code if we would use the `clamp` function from lodash here instead. That way we can remove the checks and simply limit the value to a valid range when updating the query.

You are right, i didn't realize lodash was already used, i replaced it with `clamp` and now the code needs a little less modification and looks cleaner
> It would also be nice if you could define a const like `MAX_STEP_COUNT` on top and use that instead of the magic number 50. ;)

I originally thought of it, but it seemed a bit unnecessary to me for a value that it's only used once, but i ended up adding it in the end
> Another minor thing I noticed is that now that we're limiting the number of steps to be at least 2 we can't type something like `10` or `15` into the steps input because it's immediately changed to 2. But you don't have to tackle that if you don't want to.

Oops, i missed that, now it has a debounce so it should do the trick.

Thanks for the feedback! :D

**Comment by pabueco** [comment]
Very nice, thanks for implementing the suggestions!

**Comment by pabueco** [comment]
However I'm not too sure about the debounce to be honest. Because now it's possible again to type in a really large number and more or less break the app because the check runs after everything has already started rendering.

If you have another idea on how to solve that I would love to see it. Otherwise I can merge it for now and think about a fix for that later. :D

**Comment by santiagovrancovich** [comment]
Well limiting the amount of steps that can be rendered could be a fix to that, a simple `clamp` on the render function will do that.

**Comment by pabueco** [comment]
Nice, thanks for your work.

**Pull request merged**
